ECommerce/ECommerce/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ECommerce.Data;
using ECommerce.Models;
using ECommerce.Models.Services;
using Microsoft.AspNetCore.Identity;
using ECommerce.Models.Interfaces;
using Microsoft.AspNetCore.Authorization;

namespace ECommerce.Controllers
{
    public class CartsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IUser _User;
        private readonly ICart _Cart;
        public CartsController(ApplicationDbContext context,IUser User, ICart cart)
        {
            _context = context;
            _User = User;
            _Cart = cart;
        }


        // GET: Carts
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var user = await _User.GetUser(User);
            if (user == null)
            {
                return RedirectToAction("Login", "Account"); // Redirect to login page if the user is not authenticated
            }
           
            var productsInCart = await _Cart.GetProductsInCartAsync(user.Id);

            return View(productsInCart);
        }

        //public int GetProductsCount(string Username)
        //{ 
        //int products = _Cart.GetCartItemCountAsync(Username);
        //    return products;
        //}

        public async Task<IActionResult> GetCartItemCount()
        {
            if (User.Identity.IsAuthenticated)
            {
                var cartItemCount = await _Cart.GetCartItemCountAsync(User.Identity.Name);
                return Json(new { cartItemCount });
            }

            // Handle the case where the user is not authenticated (return 0 or an error).
            return Json(new { cartItemCount = 0 });
        }


        // GET: Carts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.carts == null)
            {
                return NotFound();
            }

            var cart = await _context.carts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cart == null)
            {
                return NotFound();
            }

            return View(cart);
        }

        // GET: Carts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Carts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserId,TotalPrice,Count")] Cart cart)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cart);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cart);
        }

        // GET: Carts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.carts == null)
            {
                return NotFound();
            }

            var cart = await _context.carts.FindAsync(id);
            if (cart == null)
            {
                return NotFound();
            }
            return View(cart);
        }

        // POST: Carts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserId,TotalPrice,Count")] Cart cart)
        {
            if (id != cart.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cart);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CartExists(cart.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cart);
        }

        // GET: Carts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.carts == null)
            {
                return NotFound();
            }

            var cart = await _context.carts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cart == null)
            {
                return NotFound();
            }

            return View(cart);
        }

        // POST: Carts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.carts == null)
            {
                return Problem("Entity set 'ApplicationDbContext.carts'  is null.");
            }
            var cart = await _context.carts.FindAsync(id);
            if (cart != null)
            {
                _context.carts.Remove(cart);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CartExists(int id)
        {
          return (_context.carts?.Any(e => e.Id == id)).GetValueOrDefault();
        }


        // CartService.cs
       

    }
}

ECommerce/ECommerce/Views/Shared/LoginInfo.cshtml
@inject Microsoft.AspNetCore.Identity.SignInManager<ApplicationUser> _signinManager
<style>
    li a .badge {
        font-size: 15px;
        font-weight: bold !important;
        color: red !important;

        
    }

    .btn {
    font-weight:bold;
    
    }
  
</style>

<ul class="navbar-nav ms-auto">
    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
    {
        <li class="nav-item">
            <a class="btn btn-outline-success me-2" asp-controller="Main" asp-action="Register">Register</a>

        </li>

    }
    @if (User.Identity.IsAuthenticated)
    {

        
        <li class="nav-item">
            <a class="nav-link" asp-controller="Carts" asp-action="Index">
                My Cart  
            </a>
        </li>
       
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button"
               data-bs-toggle="dropdown" aria-expanded="false">
                Hello @(User.FindFirst("UserFirstName").Value + " " + User.FindFirst("UserLastName").Value)
            </a>
            <ul class="dropdown-menu custom-dropdown" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" asp-controller="Main" asp-action="Profile">Profile</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" asp-controller="Main" asp-action="Logout">Logout</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" asp-controller="Account" asp-action="ChangePassword">Change Password</a></li>
            </ul>
        </li>

      

    }
    else
    {
        <li class="nav-item">
            <a class="btn btn-outline-success me-2" asp-controller="Main" asp-action="Register">Register</a>
            <a class="btn btn-outline-primary" asp-controller="Main" asp-action="Login">Login</a>
        </li>
    }
</ul>










@* cart proxy code*@

@*  (<span id="cartItemCount" class="badge badge-danger">0</span>)  *@
 @* @if (User.Identity.IsAuthenticated)
{
    <script>
        function updateCartItemCount(count) {
            var cartItemCountElement = document.getElementById("cartItemCount");
            if (cartItemCountElement) {
                cartItemCountElement.textContent = count;
            }
        }

        updateCartItemCount(@Model.Count);
    </script>
} *@
 

ECommerce/ECommerce/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ECommerce</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ECommerce.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ECommerce</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ECommerce - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ECommerce/ECommerce/Views/Shared/_Layout1.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1" lang="en" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/LayoutStyle1.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-KyZXEAg3QhqLMpG8r+Q6w6fP6s3Pn+e+RaYoKTV2y4++ktY/0gRFYwkslD9fy8+vCaM6tm/3lL1Od26vr0/vMg==" crossorigin="anonymous" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top p-2">
            <a class="navbar-brand" asp-controller="Main" asp-action="Index">
                <img src="~/Images/565.jpg" width="35" height="35">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/about">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#Services">Services</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Main" asp-action="SendEmail">ContactUs</a>
                    </li>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Products" asp-action="ViewAllProducts">View All Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Products" asp-action="Create">Add New Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Categories" asp-action="Index">Categories</a>
                        </li>
                    }

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="Search-item">
                            <form method="get" asp-controller="Products" asp-action="Rows">
                                <div class="input-group field FormWidth">
                                    <input class="form-control rounded" type="text" name="productname" placeholder="Search for a product" required />
                                    <div class="input-group-append">
                                        <button class="btn btn-primary search-btn" type="submit">Search</button>
                                    </div>
                                </div>
                            </form>
                        </li>

                    }

                </ul>
                <ul class="ms-auto"> <partial name="LoginInfo" /> </ul>
            </div>
        </nav>
    </header>
    <div>
        <main role="main">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>